[theme]
primaryColor = "#387ed1"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
