[theme]
primaryColor = "#4d65ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f5f7"
textColor = "#011f24"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
